config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords'
                                  }
  devise_scope :user do
    root 'users/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    patch 'users/confirm' => 'users/confirmations#confirm'
  end

  resources :dashboard
  resources :categories
  resources :animation_datas
  resources :user_animations, except: [:show]

  post "my_animation/new" => "animation_datas#create"
  get "my_animations" => "animation_datas#my_animations"

  get 'user_animations/:id' => 'user_animations#inactive'
  get 'users_details' => 'dashboard#users_details'
  get 'order_details' => 'dashboard#order_details'

  scope "/categories/:id/" do
    get "sub_categories" => 'categories#show'
    get "new" => 'categories#new_sub_category', as: :new_sub_category
    post "new" => 'categories#create_sub_category'

    scope "sub_categories/:sub_category_id/" do
      get "animations" => 'animation_datas#show'
      get "new" => 'animation_datas#new', as: :new_animation
      post "new" => 'animation_datas#create'

      get "edit" => "categories#edit_sub_category", as: :edit_sub_category
      patch "edit" => "categories#update_sub_category"
      delete "destroy" => "categories#destroy_sub_category", as: :destroy_sub_category

        scope "animations/:animation_data_id" do
            get "purchase" => 'user_animations#new'
            get "demo" => 'animation_datas#demo'

            get "edit" => 'animation_datas#edit', as: "edit_animation"
            patch "edit" => 'animation_datas#update'
            delete 'destroy' => 'animation_datas#destroy', as: :destroy_animation
        end
    end
  end

  scope "animations/:animation_data_id" do
    get "user_animation_demo" => 'animation_datas#demo'
    get "purchase_user_animation" => 'user_animations#new'
  end

  namespace :api do
    namespace :v1 do
      resources :animation_datas
      get '/animation_datas' , to: 'animation_datas#index'
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true
class DashboardController < ApplicationController

  def users_details
    authorize :dashboard, :users_details?
    @users = User.all
  end
  def order_details
    authorize :dashboard, :order_details?
    @orders = UserAnimation.all
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/index.html.haml
.container-fluid.h-75
  - if current_user.role == 'user'
    %h2.text-center.m-3
      User Dashboard
    .row
      .col.col-lg-8.offset-lg-2.bg-light.text-center
        NOTE: Make sure you have included
        %code &lt;script src="192.168.1.100:3000/users/#{current_user.uuid}.min.js"&gt
        in your application.
  .row.mt-4
    .col-lg-6.offset-lg-3.p-4.text-center
      %h2 Our Animations
      .row.pt-5.pb-5
        .col-lg-4.offset-lg-4
          = button_to 'Our Animations', categories_path, method: "get", class: "btn btn-success"
          %br
          - if current_user.role == 'user'
            = button_to 'Add Animations', new_animation_data_path, method: "get", class: "btn btn-success"

app/views/dashboard/order_details.html.haml
.col-md-4.offset-md-4.text-center
  %h3 Order Details
  %table.table.table-hover.table-responsive
    %thead.thead-dark
      %tr
        %th Name
        %th Animation Id
        %th Start Date
        %th End Date
    - @orders.each do |order|
      %tr
        %td
          =order.user.first_name+' '+order.user.last_name
        %td
          =order.animation_data_id
        %td
          =order.start_date
        %td
          =order.end_date

app/views/dashboard/users_details.html.haml
.col-md-4.offset-md-4.text-center
  %h2 Users Details
.col-md-6.offset-md-3
  %table.table.table-hover.table-responsive
    %thead.thead-dark
      %tr
        %th Id
        %th Name
        %th Email
        %th Contact
    - @users.each do |user|
      %tr
        %td
          =user.id
        %td
          =user.first_name+' '+user.last_name
        %td
          =user.email
        %td
          =user.contact_number