config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords'
                                  }
  devise_scope :user do
    root 'users/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    patch 'users/confirm' => 'users/confirmations#confirm'
  end

  resources :dashboard
  resources :categories
  resources :animation_datas
  resources :user_animations, except: [:show]

  post "my_animation/new" => "animation_datas#create"
  get "my_animations" => "animation_datas#my_animations"

  get 'user_animations/:id' => 'user_animations#inactive'
  get 'users_details' => 'dashboard#users_details'
  get 'order_details' => 'dashboard#order_details'

  scope "/categories/:id/" do
    get "sub_categories" => 'categories#show'
    get "new" => 'categories#new_sub_category', as: :new_sub_category
    post "new" => 'categories#create_sub_category'

    scope "sub_categories/:sub_category_id/" do
      get "animations" => 'animation_datas#show'
      get "new" => 'animation_datas#new', as: :new_animation
      post "new" => 'animation_datas#create'

      get "edit" => "categories#edit_sub_category", as: :edit_sub_category
      patch "edit" => "categories#update_sub_category"
      delete "destroy" => "categories#destroy_sub_category", as: :destroy_sub_category

        scope "animations/:animation_data_id" do
            get "purchase" => 'user_animations#new'
            get "demo" => 'animation_datas#demo'

            get "edit" => 'animation_datas#edit', as: "edit_animation"
            patch "edit" => 'animation_datas#update'
            delete 'destroy' => 'animation_datas#destroy', as: :destroy_animation
        end
    end
  end

  scope "animations/:animation_data_id" do
    get "user_animation_demo" => 'animation_datas#demo'
    get "purchase_user_animation" => 'user_animations#new'
  end

  namespace :api do
    namespace :v1 do
      resources :animation_datas
      get '/animation_datas' , to: 'animation_datas#index'
    end
  end
end

app/models/animation_data.rb
# frozen_string_literal: true

class AnimationData < ApplicationRecord
  validates :animation_name, :animation_price, :picture, :animation_json, presence: true
  mount_uploader :picture, PictureUploader
  belongs_to :category, optional: true
  belongs_to :user
  has_many :user_animations
  has_many :users, through: :user_animations

  def user_private_animation?
    category_id.nil?
  end

  def purchase_private_animation?
    user_private_animation? and user.role == 'user'
  end
end

app/controllers/animation_datas_controller.rb
# frozen_string_literal: true
class AnimationDatasController < ApplicationController

  def show
    @animations = AnimationData.where(category_id: params[:sub_category_id]).order(id: :ASC)

    if @animations.empty?
      flash[:alert] = t('animation_not_found')
      redirect_to sub_categories_path
    else
      sub_category = Category.find(params[:sub_category_id])
      add_breadcrumb "Category", categories_path
      add_breadcrumb sub_category.primarycategory.category_name, sub_categories_path
      add_breadcrumb sub_category.category_name
    end
    @primary_category_id = params[:id]
    @secondary_category_id = params[:sub_category_id]
  end

  def demo
    @animation = AnimationData.find_by(id: params[:animation_data_id])
    if (@animation.nil?)
      flash[:alert] = t('animation_not_found')
      redirect_to animations_path
    else
      @animation_json = @animation.animation_json.to_json
    end
  end

  def new
    @new_animation = AnimationData.new
    authorize @new_animation
  end

  def create
    if (!params[:animation_datas].nil? and !params[:animation_datas][:animation_json].nil?)
      file_data = params[:animation_datas][:animation_json].read
      params[:animation_datas][:animation_json] = file_data.as_json
      params[:animation_datas][:category_id] = params[:sub_category_id]
      params[:animation_datas][:animation_json].force_encoding("UTF-8")
      if AnimationData.create(permit_params)
        flash[:notice] = t('create_success')
        redirect_to animations_path
      end
    else
      flash[:alert] = t('create_error')
      render :new
    end
  end

  def edit
    @animation = AnimationData.find_by(id: params[:animation_data_id])
    if @animation.nil?
      flash[:alert] = t('animation_not_found')
      redirect_to animations_path
    end
  end

  def update
    unless params[:animation_datas][:animation_json].nil?
      file_data = params[:animation_datas][:animation_json].read
      params[:animation_datas][:animation_json] = file_data.as_json
      params[:animation_datas][:animation_json].force_encoding("UTF-8")
    end
    AnimationData.find_by(id: params[:animation_data_id]).update(permit_params)
    flash[:notice] = t('update_success')
    redirect_to animations_path
  end

  def destroy
    animation = AnimationData.find_by(id: params[:animation_data_id])
    if animation.present?
      animation.destroy ? flash[:alert] = t('delete_success') : flash[:alert] = t('delete_error')
    else
      flash[:alert] = t('animation_not_found')
    end
      redirect_to animations_path
  end

  private
    def permit_params
      params.require(:animation_datas).permit(:animation_name, :animation_price,:category_id,:picture, :animation_json)
    end
end

app/controllers/api/v1/animation_datas_controller.rb
module Api
  module V1
    class AnimationDatasController < ApplicationController
      skip_before_action :authenticate_user!
      def index
        user = User.where(uuid: params['uuid']).first
        return render json: {} unless user.present?
        @animation_record = UserAnimation.
          where('start_date <= :today_date AND end_date >= :today_date', today_date: Date.today).
          where(user_id: user, location: params['location']).first
        if @animation_record
          @animation = AnimationData.find(@animation_record.animation_data_id).animation_json
          render json: { animation: @animation.as_json, frequency: @animation_record.frequency }
        else
          render json: {}
        end
      end
    end
  end
end

app/controllers/api/v2/animation_datas_controller.rb
module Api
    module V2
        class AnimationDatasController < ApplicationController

            def index
              @animation = AnimationData.where(category_id: params[:category_id])
              render json: {data: @animation}
            end
            
        end
    end
end

app/helpers/animation_datas_helper.rb
# frozen_string_literal: true

module AnimationDatasHelper
end

app/views/animation_datas/_animationdata.html.haml
- n = 0
- count = @animations.count
- outer = (count - 1) / 4 + 1
.container-fluid.justify-content-center
  - outer.times do
    .row.justify-content-left.my-4
      - 4.times do
        - break if n >= count
        .card.col-md-3.p-3.text-center{:style => "height: 28rem"}
          %img.img-fluid{:alt => "hii", :src => "#{@animations[n].picture.url}", :style => "height: 50%"}
          .card-body
            %h5.card-title.text-center.my-4= @animations[n].animation_name
            %p.card-text.text-center.my-4 Animation Price: #{@animations[n].animation_price}
            - if @animations[n].user_private_animation?
              = button_to 'Show Demo', user_animation_demo_path(@animations[n].id), method: "get", class: "btn btn-primary", :style => "float: left"
            - else
              = button_to 'Show Demo', demo_path(@primary_category_id, @secondary_category_id, @animations[n].id), method: "get", class: "btn btn-primary", :style => "float: left"
            - if @animations[n].purchase_private_animation?
              = button_to 'Purchase', purchase_user_animation_path(@animations[n].id), method: "get", class: "btn btn-success"
            - else
              = button_to 'Purchase', purchase_path(@primary_category_id, @secondary_category_id, @animations[n].id), method: "get", class: "btn btn-success"
            - if current_user.role == "admin"
              = button_to 'Delete', destroy_animation_path(@primary_category_id, @secondary_category_id, @animations[n].id), method: "delete", data: { confirm: "Do you want to delete ?" }, class: "btn btn-danger", :style => "float: right"
              = button_to 'Edit', edit_animation_path(@primary_category_id, @secondary_category_id, @animations[n].id), method: "get", class: "btn btn-success"
        - n+=1

app/views/animation_datas/demo.html.haml
=javascript_pack_tag 'demo_animation'
%body{onload: "show(animation)"}
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title W3.CSS Template
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Karma", :rel => "stylesheet"}/
  %body
  %br
  %br
    %center
      .jumbotron
        %h1{style:'font-size:100px'} Josh Foods!
        %p.lead This is a site displaying food items.
        %hr.my
        %p It works considering user food tasting experience.
        %p.lead
    .w3-main.w3-content.w3-padding{:style => "max-width:1200px;margin-top:100px"}
      #food.w3-row-padding.w3-padding-16.w3-center
        .w3-quarter
          %img{:alt => "Sandwich", :src => image_url("1.jpeg"), :style => "width:100%"}/
          %h3 The Perfect Sandwich, A Real NYC Classic
          %p Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.
          %button.btn.btn-info.btn-md{:onclick => "myFunction()"} Click Here
          :javascript
            function myFunction() {
              alert("I am an alert box!");
            }
        .w3-quarter
          %img{:alt => "Steak", :src => image_url("16.jpeg"), :style => "width:100%"}/
          %h3 Let Me Tell You About This Steak
          %p Once again, some random text to lorem lorem lorem lorem ipsum text.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Cherries", :src => image_url("3.jpeg"), :style => "width:100%"}/
          %h3 Cherries, interrupted and Vegetables
          %p Lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Pasta and Wine", :src => image_url("4.jpeg"), :style => "width:100%"}/
          %h3 Once Again, Robust Wine and Vegetable Pasta
          %p Lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
      / Second Photo Grid
      .w3-row-padding.w3-padding-16.w3-center
        .w3-quarter
          %img{:alt => "Popsicle", :src => image_url("5.jpeg"), :style => "width:100%"}/
          %h3 All I Need Is a Popsicle
          %p Lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Salmon", :src => image_url("6.jpeg"), :style => "width:100%"}/
          %h3 Salmon For Your Skin
          %p Once again, some random text to lorem lorem lorem lorem ipsum text praesent.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Sandwich", :src => image_url("7.jpeg"), :style => "width:100%"}/
          %h3 The Perfect Sandwich
          %p Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Croissant", :src => image_url("8.jpeg"), :style => "width:100%"}/
          %h3 Le French
          %p Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

        .w3-row-padding.w3-padding-16.w3-center
        .w3-quarter
          %img{:alt => "Popsicle", :src => image_url("9.jpeg"), :style => "width:100%"}/
          %h3 All I Need Is a Popsicle
          %p Lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Salmon", :src => image_url("10.jpeg"), :style => "width:100%"}/
          %h3 Salmon For Your Skin
          %p Once again, some random text to lorem lorem lorem lorem ipsum text praesent.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Sandwich", :src => image_url("11.jpeg"), :style => "width:100%"}/
          %h3 The Perfect Sandwich
          %p Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Croissant", :src => image_url("12.jpeg"), :style => "width:100%"}/
          %h3 Le French
          %p Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

        .w3-row-padding.w3-padding-16.w3-center
        .w3-quarter
          %img{:alt => "Popsicle", :src => image_url("13.jpeg"), :style => "width:100%"}/
          %h3 All I Need Is a Popsicle
          %p Lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Salmon", :src => image_url("14.jpeg"), :style => "width:100%"}/
          %h3 Salmon For Your Skin
          %p Once again, some random text to lorem lorem lorem lorem ipsum text praesent.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Sandwich", :src => image_url("15.jpeg"), :style => "width:100%"}/
          %h3 The Perfect Sandwich
          %p Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        .w3-quarter
          %img{:alt => "Croissant", :src => image_url("16.jpeg"), :style => "width:100%"}/
          %h3 Le French
          %p Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.
          .container
            %button.btn.btn-info.btn-md{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"} Click Here
            #myModal.modal.fade{role: "dialog"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %p Some text in the modal.
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
  %footer.section.footer-classic.context-dark.bg-image{style: "background: lightgrey;"}
    .container
      .row.row-30
        .col-md-4.col-xl-5
          .pr-xl-4
            %a.brand{href: "index.html"}

            %p We are an award-winning creative agency, dedicated to the best result in web design, promotion, business consulting, and marketing.
            / Rights
            %p.rights
              %span © 
              %span.copyright-year 2018
              %span  
              %span Waves
              %span . 
              %span All Rights Reserved.
        .col-md-4
          %h5 Contacts
          %dl.contact-list
            %dt Address:
            %dd 798 South Park Avenue, Jaipur, Raj
        .col-md-4.col-xl-3
          %h5 Links
          %ul.nav-list
            %li
              %a{href: "#"} About
            %li
              %a{href: "#"} Projects
            %li
              %a{href: "#"} Blog
            %li
              %a{href: "#"} Contacts
            %li
              %a{href: "#"} Pricing
:javascript
  window.animation = #{@animation_json.html_safe}

app/views/animation_datas/edit.html.haml
.container-fluid
  .row
    .col-md-4.offset-md-4
      %h3 Edit Animation Form
      = bootstrap_form_with scope: :animation_datas, method:"patch", url: edit_animation_path, local: true do |form|
        %p
          = form.text_field :animation_name, required: true, value: @animation.animation_name
        %p
          = form.text_field :animation_price, required: true, value: @animation.animation_price
        %label Your Previous picture
        %img.img-fluid{:alt => "hii", :src => "#{@animation.picture.url}", id: "new_picture"}
        %p
          = form.file_field :picture, id:"picture", onchange: "picture_file(this)", accept: 'image/png,image/gif,image/jpeg'
        %p
          = form.file_field :animation_json, id:"json", onchange: "json_file(this)"
        %p
          = form.submit
      = button_to 'Cancel',animations_path, method: "get", class: "btn btn-success", :style => "float: left"


:javascript
  function picture_file(element){
    var fileName = document.getElementById("picture").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }
  function json_file(element){
    var fileName = document.getElementById("json").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }

app/views/animation_datas/my_animations.html.haml
%div.offset-sm-11
  = link_to 'Back', dashboard_index_path, class: "btn btn-success"
= render partial: 'animationdata'

app/views/animation_datas/new.html.haml
%div.offset-sm-11
  - if current_user.role == 'admin'
    = link_to 'Back', animations_path, class: "btn btn-success"
    - path = new_animation_path
  - else
    = link_to 'Back', dashboard_index_path, class: "btn btn-success"
    - path = my_animation_new_path
.container-fluid
  .row
    .col-md-4.offset-md-4
      %h3 New Animation Form
      = bootstrap_form_with scope: :animation_datas, url: path, local: true do |form|
        %p
          = form.text_field :animation_name, required: true
        %p
          = form.text_field :animation_price, required: true
        %p
          = form.file_field :picture, required: true, id:"picture", onchange: "picture_file(this)"
        %p
          = form.file_field :animation_json, required: true, id:"json", onchange: "json_file(this)"
        %p
          = form.submit


:javascript
  function picture_file(element){
    var fileName = document.getElementById("picture").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }
  function json_file(element){
    var fileName = document.getElementById("json").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }

app/views/animation_datas/show.html.haml
= render_breadcrumbs
%div.offset-sm-11
- if current_user.role == "admin"
  = button_to 'Add New Animation', new_animation_path, method: "get", class: "btn btn-primary"
= render partial: 'animationdata'