config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords'
                                  }
  devise_scope :user do
    root 'users/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    patch 'users/confirm' => 'users/confirmations#confirm'
  end

  resources :dashboard
  resources :categories
  resources :animation_datas
  resources :user_animations, except: [:show]

  post "my_animation/new" => "animation_datas#create"
  get "my_animations" => "animation_datas#my_animations"

  get 'user_animations/:id' => 'user_animations#inactive'
  get 'users_details' => 'dashboard#users_details'
  get 'order_details' => 'dashboard#order_details'

  scope "/categories/:id/" do
    get "sub_categories" => 'categories#show'
    get "new" => 'categories#new_sub_category', as: :new_sub_category
    post "new" => 'categories#create_sub_category'

    scope "sub_categories/:sub_category_id/" do
      get "animations" => 'animation_datas#show'
      get "new" => 'animation_datas#new', as: :new_animation
      post "new" => 'animation_datas#create'

      get "edit" => "categories#edit_sub_category", as: :edit_sub_category
      patch "edit" => "categories#update_sub_category"
      delete "destroy" => "categories#destroy_sub_category", as: :destroy_sub_category

        scope "animations/:animation_data_id" do
            get "purchase" => 'user_animations#new'
            get "demo" => 'animation_datas#demo'

            get "edit" => 'animation_datas#edit', as: "edit_animation"
            patch "edit" => 'animation_datas#update'
            delete 'destroy' => 'animation_datas#destroy', as: :destroy_animation
        end
    end
  end

  scope "animations/:animation_data_id" do
    get "user_animation_demo" => 'animation_datas#demo'
    get "purchase_user_animation" => 'user_animations#new'
  end

  namespace :api do
    namespace :v1 do
      resources :animation_datas
      get '/animation_datas' , to: 'animation_datas#index'
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :category_name, :category_description, :picture, presence: true
  mount_uploader :picture, PictureUploader
  has_many :animation_datas, :dependent => :destroy
  has_many :secondary_categories, class_name: 'Category', foreign_key: 'primarycategory_id', :dependent => :destroy
  belongs_to :primarycategory, class_name: 'Category', optional: true

  scope :primary, -> { where(primarycategory_id: nil) }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController

  add_breadcrumb "Category", :categories_path
  def index
    @categories = Category.primary.order(id: :ASC)
  end

  def new
    @primary_category = Category.new
    authorize @primary_category
  end

  def create
    @primary_category = Category.new(permit_params)
    if @primary_category.save
      flash[:notice] = t('create_success')
      redirect_to categories_path
    else
      flash[:alert] = t('create_error')
      render :new
    end
  end

  def show
    @primary_category = Category.find_by(id: params[:id])
    if !@primary_category.nil? and @primary_category.primarycategory_id.nil?
      add_breadcrumb "#{@primary_category['category_name']}", sub_categories_path
      @categories = @primary_category.secondary_categories.order(id: :ASC)
    else
      flash[:alert] = t('category_not_found')
      redirect_to categories_path
    end
  end

  def new_sub_category
    @new_sub_category = Category.new
    authorize @new_sub_category
    @primary_category_id = params[:id]
  end

  def create_sub_category
    @new_sub_category = Category.new(permit_params)
    @new_sub_category.primarycategory_id = params[:id]
    @new_sub_category.save ? flash[:notice] = t('create_success') : flash[:alert] = t('create_error')
    redirect_to sub_categories_path
  end

  def edit
    @edit_primary_category = Category.find_by(id: params[:id])
    if @edit_primary_category.nil?
      flash[:alert] = t('category_not_found')
      redirect_to categories_path
    end
  end

  def update
    category = Category.find_by(id: params[:id])
    if category.present?
      if category.update(permit_params)
        flash[:notice] = t('update_success')
        redirect_to categories_path
      else
        flash[:alert] = t('update_error')
        render :edit
      end
    else
      flash[:alert] = t('category_not_found')
      redirect_to categories_path
    end
  end

  def edit_sub_category
    if Category.where(id: params[:id]).exists?
      @edit_sub_category = Category.find_by(id: params[:sub_category_id])
      if @edit_sub_category.nil?
        flash[:alert] = t('category_not_found')
        redirect_to sub_categories_path
      end
    else
      flash[:alert] = t('category_not_found')
      redirect_to sub_categories_path
    end
  end

  def update_sub_category
    category = Category.find_by(id: params[:sub_category_id])
    if category.present?
      category.update(permit_params) ?
       flash[:notice] = t('update_success') : flash[:alert] = t('update_error')
    else
      flash[:alert] = t('category_not_found')
    end
    redirect_to sub_categories_path
  end

  def destroy
    category = Category.find_by(id: params[:id])
    if category.present?
      category.destroy ? flash[:alert] = t('delete_success') : flash[:alert] = t('delete_error')
    else
      flash[:alert] = t('category_not_found')
    end
    redirect_to categories_path
  end

  def destroy_sub_category
    category = Category.find_by(id: params[:sub_category_id])
    if category.present?
      category.destroy ? flash[:alert] = t('delete_success') : flash[:alert] = t('delete_error')
    else
      flash[:alert] = t('category_not_found')
    end
    redirect_to sub_categories_path
  end

  private
    def permit_params
      params.require(:category).permit(:category_name, :category_description, :picture)
    end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/edit.html.haml
.container-fluid
  .row
    .col-md-4.offset-md-4
      %h1 Add Primary Category
      = bootstrap_form_with scope: :category, method:"patch", url: category_path, local: true do |form|
        %p
          = form.text_field :category_name, value: @edit_primary_category.category_name, required: true
        %p
          = form.text_field :category_description, value: @edit_primary_category.category_description, required: true
        %label Your Previous picture
        %img.img-fluid{:alt => "alt", :src => "#{@edit_primary_category.picture.url}", :style => "height: 10%", id: "new_picture"}
        %p
          = form.file_field :picture, id: "picture", onchange: "picture_file(this)"
        %p
          = form.submit
      = button_to 'Cancel', categories_path, method: "get", class: "btn btn-success", :style => "float: left"
:javascript
  function picture_file(element){
    var fileName = document.getElementById("picture").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }

app/views/categories/edit_sub_category.html.haml
.container-fluid
  .row
    .col-md-4.offset-md-4
      %h4 Please Fill form to update #{@edit_sub_category.category_name}
      = bootstrap_form_with scope: :category, method:"patch", url: edit_sub_category_path, local: true do |form|
        %h6 Primary Category :  #{@edit_sub_category.primarycategory.category_name}
        %p
          = form.text_field :category_name, value: @edit_sub_category.category_name, required: true
        %p
          = form.text_field :category_description, value: @edit_sub_category.category_description, required: true
          %label Your Previous picture
          %img.img-fluid{:alt => "hii", :src => "#{@edit_sub_category.picture.url}", :style => "height: 10%", id: "new_picture"}
        %p
          = form.file_field :picture, id: "picture", onchange: "picture_file(this)"
        %p
          = form.submit
      = button_to 'Cancel', sub_categories_path, method: "get", class: "btn btn-success", :style => "float: left"
:javascript
  function picture_file(element){
    var fileName = document.getElementById("picture").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }

app/views/categories/index.html.haml
= render_breadcrumbs
%div.offset-sm-11
- if current_user.role == "admin"
  = button_to 'New Category', new_category_path, method: "get", class: "btn btn-primary"
- n = 0
- count = @categories.count
- outer = (count - 1) / 4 + 1
.container-fluid.justify-content-center
  - outer.times do
    .row.justify-content-left.my-4
      - 4.times do
        - break if n >= count
        .card.col-md-3.p-3.text-center{:style => "height: 32rem"}
          %img.img-fluid{:alt => "hii", :src => "#{@categories[n].picture.url}", :style => "height: 40%"}
          %h5.card-title.text-center.pt-3= @categories[n].category_name
          .card-body.justify-content-center.overflow-auto.m-0.p-0
            %p.card-text.text-muted.text-center= @categories[n].category_description
            - if current_user.role == "user"
              = button_to 'View', sub_categories_path(@categories[n].id), method: "get", class: "btn btn-info"
            - if current_user.role == "admin"
              = button_to 'View', sub_categories_path(@categories[n].id), method: "get", class: "btn btn-info", :style => "float: left"
              = button_to 'Delete', category_path(@categories[n].id), method: "delete", data: { confirm: "Do you want to delete ?" }, class: "btn btn-danger", :style => "float: right"
              = button_to 'Edit', edit_category_path(@categories[n].id), method: "get", class: "btn btn-success"
        - n+=1

app/views/categories/new.html.haml
.container-fluid
  .row
    .col-md-4.offset-md-4
      %h1 Add Primary Category
      = bootstrap_form_with scope: :category, url: categories_path,local: true do |form|
        %p
          = form.text_field :category_name, required: true
        %p
          = form.text_field :category_description, required: true
        %p
          = form.file_field :picture, id: "picture", onchange: "picture_file(this)", required: true
        %p
          = form.submit
      = button_to 'Cancel', categories_path, method: "get", class: "btn btn-success", :style => "float: left"

:javascript
  function picture_file(element){
    var fileName = document.getElementById("picture").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }

app/views/categories/new_sub_category.html.haml
.container-fluid
  .row
    .col-md-4.offset-md-4
      %h3 New Sub Category
      = bootstrap_form_with scope: :category, url: new_sub_category_path(@primary_category_id),local: true do |form|
        %p
          = form.text_field :category_name, required: true
        %p
          = form.text_field :category_description, required: true
        %p
          = form.file_field :picture, required: true, onchange: "picture_file(this)", id: "picture"
        %p
          = form.submit
      = button_to 'Cancel', sub_categories_path, method: "get", class: "btn btn-success", :style => "float: left"

:javascript
  function picture_file(element){
    var fileName = document.getElementById("picture").files[0].name;
    var nextSibling = element.nextElementSibling;
    nextSibling.innerText = fileName;
  }

app/views/categories/show.html.haml
= render_breadcrumbs
%div.offset-sm-11
- if current_user.role == "admin"
  = button_to 'New Sub_category', new_sub_category_path(@primary_category), method: "get", class: "btn btn-primary"
- n = 0
- count = @categories.count
- outer = (count - 1) / 4 + 1
.container-fluid.justify-content-center
  - outer.times do
    .row.justify-content-left.my-4
      - 4.times do
        - break if n >= count
        .card.col-md-3.p-3.text-center{:style => "height: 32rem"}
          %img.img-fluid{:alt => "hii", :src => "#{@categories[n].picture.url}", :style => "height: 50%"}
          %h5.card-title.text-center.pt-3= @categories[n].category_name
          .card-body.justify-content-center.overflow-auto.m-0.p-0
            %p.card-text.text-muted.text-center= @categories[n].category_description
            - if current_user.role == "user"
              = button_to 'View', animations_path(@primary_category.id, @categories[n].id), method: "get", class: "btn btn-info"
            - if current_user.role == "admin"
              = button_to 'View', animations_path(@primary_category.id, @categories[n].id), method: "get", class: "btn btn-info", :style => "float: left"
              = button_to 'Delete', destroy_sub_category_path(@primary_category.id, @categories[n].id), method: "delete", data: { confirm: "Do you want to delete ?" }, class: "btn btn-danger", :style => "float: right"
              = button_to "Edit", edit_sub_category_path(@primary_category.id, @categories[n].id), method: "get", class: "btn btn-success"
        - n+=1