config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords: 'users/passwords'
                                  }
  devise_scope :user do
    root 'users/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    patch 'users/confirm' => 'users/confirmations#confirm'
  end

  resources :dashboard
  resources :categories
  resources :animation_datas
  resources :user_animations, except: [:show]

  post "my_animation/new" => "animation_datas#create"
  get "my_animations" => "animation_datas#my_animations"

  get 'user_animations/:id' => 'user_animations#inactive'
  get 'users_details' => 'dashboard#users_details'
  get 'order_details' => 'dashboard#order_details'

  scope "/categories/:id/" do
    get "sub_categories" => 'categories#show'
    get "new" => 'categories#new_sub_category', as: :new_sub_category
    post "new" => 'categories#create_sub_category'

    scope "sub_categories/:sub_category_id/" do
      get "animations" => 'animation_datas#show'
      get "new" => 'animation_datas#new', as: :new_animation
      post "new" => 'animation_datas#create'

      get "edit" => "categories#edit_sub_category", as: :edit_sub_category
      patch "edit" => "categories#update_sub_category"
      delete "destroy" => "categories#destroy_sub_category", as: :destroy_sub_category

        scope "animations/:animation_data_id" do
            get "purchase" => 'user_animations#new'
            get "demo" => 'animation_datas#demo'

            get "edit" => 'animation_datas#edit', as: "edit_animation"
            patch "edit" => 'animation_datas#update'
            delete 'destroy' => 'animation_datas#destroy', as: :destroy_animation
        end
    end
  end

  scope "animations/:animation_data_id" do
    get "user_animation_demo" => 'animation_datas#demo'
    get "purchase_user_animation" => 'user_animations#new'
  end

  namespace :api do
    namespace :v1 do
      resources :animation_datas
      get '/animation_datas' , to: 'animation_datas#index'
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title WebDecor
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.7.0/css/all.css'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'alert'
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.3/lottie.min.js"}

  %body
    - if notice
      #message.alert.alert-success
        %span.fa.fa-check-circle.fa-lg
        = notice
    - if alert
      #message.alert.alert-danger
        %span.fa.fa-exclamation-circle.fa-lg
        = alert
    - if user_signed_in?
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-3
        = link_to 'WebDecor', dashboard_index_path, class:"navbar-brand"
        - if current_user.role == "admin"
          = link_to 'User Details', users_details_path, class:"navbar-brand"
          = link_to 'Order Details', order_details_path, class:"navbar-brand"
        - else
          = link_to 'My Orders', user_animations_path, class:"navbar-brand"
          = link_to 'My Animations', my_animations_path, class:"navbar-brand"
        %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false",
        "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent",
        "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarSupportedContent.collapse.navbar-collapse
          %ul.navbar-nav.ml-auto
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false",
              "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
                = current_user.first_name+" "+current_user.last_name
              .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                = link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item'
                = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'
    = yield